[package]
name = "pathfinder-merkle-tree"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bitvec = { workspace = true }
indextree = "4.6.0"
pathfinder-common = { path = "../common" }
pathfinder-storage = { path = "../storage" }
rand = { workspace = true }
rayon = "1.8.0"
stark_curve = { path = "../stark_curve" }
stark_hash = { path = "../stark_hash" }
stark_poseidon = { path = "../stark_poseidon" }
starknet-gateway-types = { path = "../gateway-types" }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
