name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  # Enable sccache for rust builds.
  # https://github.com/Mozilla-Actions/sccache-action#rust-code
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  SCCACHE_ERROR_LOG: /tmp/sccache_log.txt
  SCCACHE_LOG: debug
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@v1
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - uses: Noelware/setup-protoc@1.1.0
      - uses: taiki-e/install-action@nextest
      - name: Compile unit tests
        run: timeout 25m cargo nextest run --all-targets --all-features --workspace --locked --no-run

      - name: Run unit tests
        run: timeout 10m cargo nextest run --no-fail-fast --all-targets --all-features --workspace --locked

      - name: sccache log
        run: cat /tmp/sccache_log.txt

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - uses: Noelware/setup-protoc@1.1.0
      - run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings -D rust_2018_idioms

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - uses: Noelware/setup-protoc@1.1.0
      - run: cargo doc --no-deps --document-private-items

  dep-sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-sort
          version: "^1.0.9"
      - run: |
          cargo sort --check --workspace

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: read msrv
        id: msrv
        run: |
          msrv=$(grep -P "rust-version =" Cargo.toml | awk '{print $3}' | tr -d '"')
          echo Found msrc: $msrv
          echo "MSRV=$msrv" >> "$GITHUB_OUTPUT"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.msrv.outputs.MSRV }}
      - uses: Noelware/setup-protoc@1.1.0
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: check
        run: cargo check

  fuzz_targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: rui314/setup-mold@v1
        with:
          mold-version: 1.4.1
          make-default: false
      - name: Enable mold
        run: |
          mkdir -p $HOME/.cargo
          cat << EOF >> $HOME/.cargo/config.toml
          [target.x86_64-unknown-linux-gnu]
          linker = "/usr/bin/clang"
          rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
          EOF

          cat $HOME/.cargo/config.toml
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - run: cargo install cargo-fuzz
      - name: stark_hash
        run: cargo fuzz build
        working-directory: crates/stark_hash

  load_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: cargo check
        run: |
          cd crates/load-test
          cargo check
